<?php
return [
  [
    'name' => 'OptionGroup_letter_to_recipient_system',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'name' => 'letter_to_recipient_system',
        'title' => 'Recipient System',
        'description' => NULL,
        'data_type' => NULL,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_letter_to_recipient_system_OptionValue_Single_Recipient',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'option_group_id.name' => 'letter_to_recipient_system',
        'label' => 'Static Recipients',
        'value' => 'Single',
        'name' => 'Single_Recipient',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
    [
    'name' => 'CustomGroup_Letter_To',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'name' => 'Letter_To',
        'title' => 'Petition Email Delivery Options',
        'extends' => 'Survey',
        'extends_entity_column_value' => NULL,
        'style' => 'Inline',
        'collapse_display' => TRUE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'weight' => 3,
        'is_active' => TRUE,
        'is_multiple' => FALSE,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => FALSE,
        'created_date' => NULL,
        'is_reserved' => TRUE,
        'is_public' => TRUE,
        'icon' => NULL,
        'extends_entity_column_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_System',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Recipient_System',
        'label' => 'Email Recipient System',
        'data_type' => 'String',
        'html_type' => 'Select',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 10,
        'help_pre' => NULL,
        'help_post' => 'Select a system for sending emails to decision-makers or the press from this petition.',
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'option_group_id.name' => 'letter_to_recipient_system',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_From_Email',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Petition_From_Email',
        'label' => 'Petition From Email Address',
        "data_type" => "String",
        "html_type" => "Text",
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 15,
        'help_pre' => NULL,
        'help_post' => "Signed petitions sent to targets will include the name of the petition signer and include the petition signer's email address in the body of the message, but the email will be sent from the email address you specify, which should use your organization's domain name. Note: sending signed petitions from the signer's email address will appear fraudelent and not be properly delivered",
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Subject',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Subject',
        'label' => 'Subject',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'weight' => 20,
        'help_pre' => NULL,
        'help_post' => 'This is the subject line for outgoing emails',
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 128,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Default_Message',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Default_Message',
        'label' => 'Default Message',
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 30,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => 'rows=4, cols=60',
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => NULL,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 10,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_To',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'To',
        'label' => 'To',
        "data_type" => "ContactReference",
        "html_type" => "Autocomplete-Select",
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 40,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 2048,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 1,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_BCC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'BCC',
        'label' => 'BCC',
        "data_type" => "ContactReference",
        "html_type" => "Autocomplete-Select",
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 50,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 1,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_MessageTemplate',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'MessageTemplate',
        'label' => 'Message Template',
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'weight' => 10,
        'help_pre' => NULL,
        'help_post' => 'Optionally, select a Message Template to use for the petition email to improve the look and feel of the messages sent.',
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'pseudoconstant' => [
          'table' => 'civicrm_msg_template',
          'keyColumn' => 'id',
          'labelColumn' => 'msg_title',
        ],
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'CustomField_Street_Address_Field', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Street_Address_Field', 
        'label' => 'Street Address Field', 
        'data_type' => 'Int', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 60, 
        'help_pre' => NULL, 
        'help_post' => "The ID number of the contact profile field storing the signer's street address.", 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => NULL, 
        'note_rows' => NULL, 
        'column_name' => 'letter_to_street_address_field', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_City_Field', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'City_Field', 
        'label' => 'City Field', 
        'data_type' => 'Int', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 70, 
        'help_pre' => NULL, 
        'help_post' => "The ID number of the contact profile field storing the signer's city.", 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => NULL, 
        'note_rows' => NULL, 
        'column_name' => 'letter_to_city_field', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_State_Province_Field', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => [ 'name' ],  
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'State_Province_Field', 
        'label' => 'State/Province Field', 
        'data_type' => 'Int', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 80, 
        'help_pre' => NULL, 
        'help_post' => "The ID number of the contact profile field storing the signer's state.", 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => NULL, 
        'note_rows' => NULL, 
        'column_name' => 'letter_to_state_province_field', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_Postal_Code_Field', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Postal_Code_Field', 
        'label' => 'Postal Code Field', 
        'data_type' => 'Int', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 90, 
        'help_pre' => NULL, 
        'help_post' => "The ID number of the contact profile field storing the signer's ZIP code.", 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => NULL, 
        'note_rows' => NULL, 
        'column_name' => 'letter_to_postal_code_field', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields',
    'entity' => 'UFGroup',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'is_active' => TRUE,
        'group_type' => [
          'Individual',
          'Contact',
        ],
        'title' => 'Petition Contact Fields',
        'frontend_title' => 'Contact Information',
        'description' => NULL,
        'help_pre' => NULL,
        'help_post' => NULL,
        'post_URL' => NULL,
        'add_captcha' => FALSE,
        'is_map' => FALSE,
        'is_edit_link' => FALSE,
        'is_uf_link' => FALSE,
        'is_update_dupe' => TRUE,
        'cancel_URL' => NULL,
        'is_cms_user' => FALSE,
        'notify' => NULL,
        'is_reserved' => FALSE,
        'name' => 'Petition_Contact_Fields',
        'is_proximity_search' => FALSE,
        'cancel_button_text' => NULL,
        'submit_button_text' => NULL,
        'add_cancel_button' => NULL,
        'limit_listings_group_id' => NULL,
        'add_to_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_First_Name',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'first_name',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'First Name',
        'field_type' => 'Individual',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Last_Name',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'last_name',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'Last Name',
        'field_type' => 'Individual',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Email',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'email',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'Email',
        'field_type' => 'Contact',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Street_Address',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'street_address',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'Street Address',
        'field_type' => 'Contact',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_City',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'city',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'City',
        'field_type' => 'Contact',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_State',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'state_province',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'State',
        'field_type' => 'Contact',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Postal_Code',
    'entity' => 'UFField',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields',
        'field_name' => 'postal_code',
        'is_active' => TRUE,
        'is_view' => NULL,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'label' => 'Postal Code',
        'field_type' => 'Contact',
        'is_multi_summary' => NULL,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
      ],
    ],
  ],
  // Note the fields below are disabled and will be purged in future
  // versions. They are kept to enable the transition to the new
  // system of targets being reference by contact.
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_Name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Recipient_Name',
        'label' => 'Recipient Name',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => 'The display name of the petition target',
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => FALSE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 128,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_Email',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To',
        'name' => 'Recipient_Email',
        'label' => 'Recipient Email',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => 'The email address of the petition target.',
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => FALSE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 128,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'MessageTemplate_SamplePetitionEmail',
    'entity' => 'MessageTemplate',
    'cleanup' => 'unused',
    'params' => [
      'version' => 4,
      'match' => ['msg_title'],
      'values' => [
        'msg_title' => 'Samle Petition Email',
        'msg_subject' => '{petitionemail.subject}',
        'msg_html' => "
<p>{capture assign=senderIdentificationBlock}{petitionemail.senderIdentificationBlock}{/capture}</p>
<p>{capture assign=message}{petitionemail.message}{/capture}</p>
<p>{\$senderIdentificationBlock|nl2br}</p>

<p>{contact.email_greeting_display}</p>

<p>{\$message|nl2br}</p>",
      ],
    ],
  ],
];
