<?php 
return [
  [
    'name' => 'OptionGroup_letter_to_recipient_system', 
    'entity' => 'OptionGroup', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'name' => 'letter_to_recipient_system', 
        'title' => 'Recipient System', 
        'description' => NULL, 
        'data_type' => NULL, 
        'is_reserved' => TRUE, 
        'is_active' => TRUE, 
        'is_locked' => FALSE,
      ],
    ],
  ], 
  [
    'name' => 'OptionGroup_letter_to_recipient_system_OptionValue_Single_Recipient', 
    'entity' => 'OptionValue', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'option_group_id.name' => 'letter_to_recipient_system', 
        'label' => 'Single Recipient', 
        'value' => 'Single', 
        'name' => 'Single_Recipient', 
        'grouping' => NULL, 
        'filter' => 0, 
        'is_default' => FALSE, 
        'description' => NULL, 
        'is_optgroup' => FALSE, 
        'is_reserved' => FALSE, 
        'is_active' => TRUE, 
        'icon' => NULL, 
        'color' => NULL, 
        'component_id' => NULL, 
        'domain_id' => NULL, 
        'visibility_id' => NULL,
      ],
    ],
  ],
    [
    'name' => 'CustomGroup_Letter_To', 
    'entity' => 'CustomGroup', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'name' => 'Letter_To', 
        'title' => 'Petition Email Delivery Options', 
        'extends' => 'Survey', 
        'extends_entity_column_value' => NULL, 
        'style' => 'Inline', 
        'collapse_display' => TRUE, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'weight' => 3, 
        'is_active' => TRUE, 
        'is_multiple' => FALSE, 
        'min_multiple' => NULL, 
        'max_multiple' => NULL, 
        'collapse_adv_display' => FALSE, 
        'created_date' => NULL, 
        'is_reserved' => TRUE, 
        'is_public' => TRUE, 
        'icon' => NULL, 
        'extends_entity_column_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_System', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Recipient_System', 
        'label' => 'Email Recipient System', 
        'data_type' => 'String', 
        'html_type' => 'Select', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => 'Select a system for sending emails to decision-makers or the press from this petition.', 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'letter_to_recipient_system', 
        'option_group_id.name' => 'letter_to_recipient_system', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Subject', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Subject', 
        'label' => 'Subject', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => TRUE, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => 'This is the subject line for outgoing emails', 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 128, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'letter_to_subject', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_Name', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Recipient_Name', 
        'label' => 'Recipient Name', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => 'The display name of the petition target', 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 128, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'letter_to_recipient_name', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Recipient_Email', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Recipient_Email', 
        'label' => 'Recipient Email', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => TRUE, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => 'The email address of the petition target.', 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 128, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'letter_to_recipient_email', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Letter_To_CustomField_Default_Message', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'Default_Message', 
        'label' => 'Default Message', 
        'data_type' => 'Memo', 
        'html_type' => 'TextArea', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => 'rows=4, cols=60', 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 10, 
        'column_name' => 'letter_to_default_message', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_To', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'To', 
        'label' => 'To', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 28, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_CC', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'CC', 
        'label' => 'CC', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 50, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Letter_To_CustomField_CC_Email', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'CC_Email', 
        'label' => 'CC Email', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 51, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => 'size=60', 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_BCC', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'BCC', 
        'label' => 'BCC', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 52, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomField_BCC_Email', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Letter_To', 
        'name' => 'BCC_Email', 
        'label' => 'BCC Email', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => FALSE, 
        'is_searchable' => FALSE, 
        'is_search_range' => FALSE, 
        'weight' => 53, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => 'size=60', 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => FALSE, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Petition_Activity_Fields', 
    'entity' => 'CustomGroup', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'name' => 'Petition_Activity_Fields', 
        'title' => 'Petition Activity Fields', 
        'extends' => 'Activity', 
        'extends_entity_column_value' => [], // See petition_civicrm_managed().
        'style' => 'Inline', 
        'collapse_display' => TRUE, 
        'help_pre' => '', 
        'help_post' => '', 
        'weight' => 44, 
        'is_active' => TRUE, 
        'is_multiple' => FALSE, 
        'min_multiple' => NULL, 
        'max_multiple' => NULL, 
        'collapse_adv_display' => FALSE, 
        'created_date' => '2022-02-25 09:28:19', 
        'is_reserved' => FALSE, 
        'is_public' => TRUE, 
        'icon' => '', 
        'extends_entity_column_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Petition_Activity_Fields_CustomField_Custom_Email_Message', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Petition_Activity_Fields', 
        'name' => 'Custom_Email_Message', 
        'label' => 'Custom Email Message', 
        'data_type' => 'Memo', 
        'html_type' => 'TextArea', 
        'default_value' => NULL, 
        'is_required' => NULL, 
        'is_searchable' => NULL, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => 'rows=4, cols=60', 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'options_per_line' => NULL, 
        'text_length' => NULL, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'custom_email_message_633', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'CustomGroup_Petition_Activity_Fields_CustomField_Custom_Email_Subject', 
    'entity' => 'CustomField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'match' => ['name'],
      'values' => [
        'custom_group_id.name' => 'Petition_Activity_Fields', 
        'name' => 'Custom_Email_Subject', 
        'label' => 'Custom Email Subject', 
        'data_type' => 'String', 
        'html_type' => 'Text', 
        'default_value' => NULL, 
        'is_required' => NULL, 
        'is_searchable' => NULL, 
        'is_search_range' => FALSE, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'mask' => NULL, 
        'attributes' => NULL, 
        'javascript' => NULL, 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'options_per_line' => NULL, 
        'text_length' => 255, 
        'start_date_years' => NULL, 
        'end_date_years' => NULL, 
        'date_format' => NULL, 
        'time_format' => NULL, 
        'note_columns' => 60, 
        'note_rows' => 4, 
        'column_name' => 'custom_email_subject_634', 
        'serialize' => 0, 
        'filter' => NULL, 
        'in_selector' => FALSE, 
        'option_group_id' => NULL,
      ],
    ],
  ],
    [
    'name' => 'UFGroup_Petition_Activity_Fields', 
    'entity' => 'UFGroup', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'is_active' => TRUE, 
        'title' => 'Petition Activity Fields', 
        'frontend_title' => NULL, 
        'description' => NULL, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'post_URL' => NULL, 
        'add_captcha' => FALSE, 
        'is_map' => FALSE, 
        'is_edit_link' => FALSE, 
        'is_uf_link' => FALSE, 
        'is_update_dupe' => FALSE, 
        'cancel_URL' => NULL, 
        'is_cms_user' => FALSE, 
        'notify' => NULL, 
        'is_reserved' => NULL, 
        'name' => 'Petition_Activity_Fields', 
        'is_proximity_search' => FALSE, 
        'cancel_button_text' => NULL, 
        'submit_button_text' => NULL, 
        'add_cancel_button' => NULL, 
        'limit_listings_group_id' => NULL, 
        'add_to_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Activity_Fields_UFField_Subject', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Activity_Fields', 
        'field_name' => 'custom_nnn',  // This gets fixed in petition_civicrm_managed()
        'field_name:name' => 'Custom_Email_Subject', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Subject', 
        'field_type' => 'Activity', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Activity_Fields_UFField_Message', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Activity_Fields', 
        'field_name' => 'custom_nnn',  // This gets fixed in petitionemail_civicrm_managed()
        'field_name:name' => 'Custom_Email_Message', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Message', 
        'field_type' => 'Activity', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields', 
    'entity' => 'UFGroup', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'is_active' => TRUE, 
        'group_type' => [
          'Individual', 
          'Contact',
        ], 
        'title' => 'Petition Contact Fields', 
        'frontend_title' => 'Contact Information', 
        'description' => NULL, 
        'help_pre' => NULL, 
        'help_post' => NULL, 
        'post_URL' => NULL, 
        'add_captcha' => FALSE, 
        'is_map' => FALSE, 
        'is_edit_link' => FALSE, 
        'is_uf_link' => FALSE, 
        'is_update_dupe' => TRUE, 
        'cancel_URL' => NULL, 
        'is_cms_user' => FALSE, 
        'notify' => NULL, 
        'is_reserved' => NULL, 
        'name' => 'Petition_Contact_Fields', 
        'is_proximity_search' => FALSE, 
        'cancel_button_text' => NULL, 
        'submit_button_text' => NULL, 
        'add_cancel_button' => NULL, 
        'limit_listings_group_id' => NULL, 
        'add_to_group_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_First_Name', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'first_name', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => TRUE, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'First Name', 
        'field_type' => 'Individual', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Last_Name', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'last_name', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => TRUE, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Last Name', 
        'field_type' => 'Individual', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Email', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'email', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => TRUE, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Email', 
        'field_type' => 'Contact', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Street_Address', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'street_address', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Street Address', 
        'field_type' => 'Contact', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_City', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'city', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'City', 
        'field_type' => 'Contact', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_State', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'state_province', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'State', 
        'field_type' => 'Contact', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ], 
  [
    'name' => 'UFGroup_Petition_Contact_Fields_UFField_Postal_Code', 
    'entity' => 'UFField', 
    'cleanup' => 'unused', 
    'update' => 'unmodified', 
    'params' => [
      'version' => 4, 
      'values' => [
        'uf_group_id.name' => 'Petition_Contact_Fields', 
        'field_name' => 'postal_code', 
        'is_active' => TRUE, 
        'is_view' => NULL, 
        'is_required' => NULL, 
        'help_post' => NULL, 
        'help_pre' => NULL, 
        'visibility' => 'User and User Admin Only', 
        'in_selector' => FALSE, 
        'is_searchable' => FALSE, 
        'label' => 'Postal Code', 
        'field_type' => 'Contact', 
        'is_reserved' => NULL, 
        'is_multi_summary' => NULL, 
        'location_type_id' => NULL, 
        'phone_type_id' => NULL, 
        'website_type_id' => NULL,
      ],
    ],
  ],
];
